free_project/formapp/urls.py
from django.urls import path
from . import views

app_name = 'formapp'

urlpatterns = [

     path('students',views.students, name='students')

    # Add more URLs as needed
]

free_project/free_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('freeapp.urls')),
    path('students/',include('formapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

free_project/freeapp/urls.py
from django.urls import path
from . import views

app_name = 'freeapp'

urlpatterns = [
    path('', views.demo, name='demo'),
    path('login/',views.log,name='login'),
    path('register/',views.regist,name='register'),
    path('computer Science/', views.one_r,name='computer Science'),
    path('biology/', views.two_r,name='biology'),
    path('maths/', views.three_r,name='maths'),
    path('commerce/', views.four_r,name='commerce'),
    path('history/', views.five_r,name='history'),
    path('student_form/', views.student_form, name='student_form'),
    path('log',views.log, name='log'),
    path('regi', views.regi, name='regi'),
    path('welcome/',views.logi,name='logi'),
    path('home/',views.hello,name='home'),
    path('logout',views.logout,name='logout'),




]

free_project/formapp/models.py
from django.db import models

# Create your models here.


class Student(models.Model):
    name = models.CharField(max_length=100)
    dob = models.DateField()
    age = models.IntegerField()
    gender = models.CharField(max_length=10)
    phone_number = models.CharField(max_length=12)
    email = models.EmailField()
    address = models.TextField()
    department = models.CharField(max_length=50)
    course = models.CharField(max_length=50)
    purpose = models.CharField(max_length=50)
    last = models.CharField(max_length=50)

    def __str__(self):
        return self.name

free_project/freeapp/models.py
from django.db import models


# Create your models here.

free_project/formapp/forms.py
from django import forms
from .models import Student


class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = '__all__'

free_project/formapp/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from formapp.models import Student


# Create your views here.

def student_form(request):
    return render(request, 'student_form.html')


def students(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        dob = request.POST.get("dob")
        age = request.POST.get("age")
        gender = request.POST.get("gender")
        phone = request.POST.get("phone")
        email = request.POST.get("email")
        address = request.POST.get("address")
        department = request.POST.get('department')
        course = request.POST.get('course')
        purpose = request.POST.get('purpose')
        last1 = request.POST.get('materials')

        student_details = Student(name=name, dob=dob, age=age, gender=gender,
                                  phone_number=phone, email=email, address=address, department=department,
                                  course=course, purpose=purpose, last=last1)
        student_details.save();
        messages.success(request,'Successfully Submitted')
        return render(request,'student_form.html')

free_project/freeapp/views.py
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.shortcuts import render, redirect, HttpResponse
from django.contrib.auth import authenticate, login

from formapp.models import Student


# Create your views here.
def demo(request):
    return render(request, 'index.html')


def student_form(request):
    return render(request, 'student_form.html')


def hello(request):
    return render(request, 'home.html')


def log(request):
    if request.method == "POST":
        username = request.POST.get("username")
        pass1 = request.POST.get("password")
        user = authenticate(request, username=username, password=pass1)
        if user is not None:
            login(request, user)
            return redirect('freeapp:home')
        else:
            messages.warning(request, "Incorrect password or Username")
            return redirect('freeapp:log')

    return render(request, 'login.html')


def logi(request):
    return render(request, 'login.html')


def regist(request):
    return render(request, 'register.html')


def regi(request):
    if request.method == 'POST':
        username = request.POST.get("username")
        pass1 = request.POST.get("password")
        pass2 = request.POST.get("password1")

        if pass1 == pass2:
            if User.objects.filter(username=username).exists():
                messages.info(request,"Username already Taken")
                return redirect('freeapp:regi')
            else:
                my_user = User.objects.create_user(username=username, password=pass1)
                my_user.save()
                return render(request, 'login.html')
        else:
            messages.info(request,"passwords are note same")
            return redirect('freeapp:regi')


    return render(request, 'register.html')


def one_r(request):
    return redirect("https://en.wikipedia.org/wiki/Computer_science")


def two_r(request):
    return redirect("https://en.wikipedia.org/wiki/Biology")


def three_r(request):
    return redirect("https://en.wikipedia.org/wiki/Business_mathematics")


def four_r(request):
    return redirect("https://en.wikipedia.org/wiki/Commerce")


def five_r(request):
    return redirect("https://en.wikipedia.org/wiki/Humanities")


def logout(request):
    return render(request,'login.html')

free_project/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <meta name="description" content="">
        <meta name="author" content="Tooplate">

        <title>School Store</title>

        <!-- CSS FILES -->
        <link rel="preconnect" href="https://fonts.googleapis.com">

        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

        <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;700&display=swap" rel="stylesheet">

        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

        <link href="{% static 'css/bootstrap-icons.css' %}" rel="stylesheet">

        <link href="{% static 'css/magnific-popup.css' %}" rel="stylesheet">

        <link href="{% static 'css/tooplate-waso-strategy.css' %}" rel="stylesheet">
        <link href="{% static 'css/nvbar.css' %}" rel="stylesheet">




    </head>

    <body id="section_1">

        <header class="site-header">
            <div class="container">
                <div class="row align-items-center">

                    <div class="col-lg-3 col-md-5 col-7">
                        <p class="text-white mb-0">
                            <i class="bi-clock site-header-icon me-2"></i>
                            Mon-Fri 10:00-19:00
                        </p>
                    </div>

                    <div class="col-lg-2 col-md-3 col-5">
                        <p class="text-white mb-0">
                            <a href="tel: 240-480-9600" class="text-white">
                                <i class="bi-telephone site-header-icon me-2"></i>
                                9562514299
                            </a>
                        </p>
                    </div>

                    <div class="col-lg-3 col-md-3 col-12 ms-auto">
                        <ul class="social-icon">
                            <li><a href="https://facebook.com" class="social-icon-link bi-facebook"></a></li>

                            <li><a href="https://pinterest.com" class="social-icon-link bi-pinterest"></a></li>

                            <li><a href="https://twitter.com" class="social-icon-link bi-twitter"></a></li>

                            <li><a href="https://www.youtube.com/@inmakeslearninghub" class="social-icon-link bi-youtube"></a></li>
                        </ul>
                    </div>

                </div>
            </div>
        </header>
        <nav class="navbar">
            <a href="#" class="navbar-brand">School <span class="text-danger">Store</span></a>
            </div>
          <ul>
              <li><a href="{% url 'freeapp:demo' %}">Home</a></li>
              <li><a href="#">Department</a>
                 <ul>
                      <li><a href="{% url 'freeapp:computer Science' %}">Computer Science</a></li>
                      <li><a href="{% url 'freeapp:biology' %}">Biology science</a></li>
                      <li><a href="{% url 'freeapp:maths' %}">Maths Commerce</a></li>
                      <li><a href="{% url 'freeapp:commerce' %}">Computer Commerce</a></li>
                      <li><a href="{% url 'freeapp:history' %}">Humanities</a></li>
                 </ul>
              </li>
              <li><a href="{% url 'freeapp:register' %}">Register</a></li>
              <li><a href="{% url 'freeapp:login' %}">LogIn</a></li>
<!--              <li><a href="#">LogOut</a></li>-->
          </ul>
        </nav>

{% block body %}
{% endblock %}
</body>
</html>

free_project/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block body %}

        <main>

            <section class="hero">
                <div class="container-fluid h-100">
                    <div class="row h-100">

                        <div id="carouselExampleCaptions" class="carousel carousel-fade hero-carousel slide" data-bs-ride="carousel">
                            <div class="carousel-inner">
                                <div class="carousel-item active">
                                    <div class="container position-relative h-100">
                                        <div class="carousel-caption d-flex flex-column justify-content-center">
                                            <small class="small-title">Introducing new courses <strong class="text-warning">01/05</strong></small>

                                            <h1>Inspiring <span class="text-warning">Lifelong</span> Learning School store</h1>

                                            <div class="d-flex align-items-center mt-4">
                                                <a class="custom-btn btn custom-link" href="{% url 'freeapp:student_form' %}">Join with us</a>


                                                </a>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="carousel-image-wrap">
                                        <img src="{% static 'images/slide/buld.jpg' %}" class="img-fluid carousel-image" alt="">
                                    </div>
                                </div>

                            </div>
                        </div>

                    </div>
                </div>
            </section>


            <section class="about section-padding" id="section_2">
                <div class="container">
                    <div class="row">

                        <div class="col-lg-6 col-12 mb-5 mb-lg-0">
                            <div class="about-image-wrap h-100">
                                <img src="{% static 'images/book.png' %}" class="img-fluid about-image" alt="">

                                <div class="about-image-info">
                                    <h4 class="text-white">School Store</h4>

                                    <p class="text-white mb-0">Describe the facilities available, such as classrooms, labs, libraries, sports facilities, etc</p>
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-6 col-12 d-flex flex-column">
                            <div class="about-thumb bg-white shadow-lg">

                                <div class="about-info">
                                    <small class="small-title">About <strong class="text-warning">02/05</strong></small>

                                    <h2 class="mb-3">School Store</h2>

                                    <h5 class="mb-3">Helping every one since 2001</h5>

                                    <p>Embark on a transformative educational journey with School Store, where excellence meets innovation, and students thrive in an environment dedicated to shaping future leaders</p>

                                    <p>You may support a little   visiting our contact page. Thank you.</p>
                                </div>
                            </div>

                            <div class="row h-100">
                                <div class="col-lg-6 col-6">
                                    <div class="about-thumb d-flex flex-column justify-content-center bg-danger mb-lg-0 h-100">

                                        <div class="about-info">
                                            <h5 class="text-white mb-4">We're growing </h5>

                                            <a class="custom-btn btn custom-bg-primary" href="{% url 'freeapp:student_form' %}">Join us</a>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-lg-6 col-6">
                                    <div class="about-thumb d-flex flex-column justify-content-center bg-warning mb-lg-0 h-100">

                                        <div class="about-info">
                                            <h5 class="text-white mb-4">How did you about us?</h5>

                                            <p class="text-white mb-0">write us</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </section>



        </main>

        <footer class="site-footer">
            <div class="container">
                <div class="row">

                    <div class="col-lg-6 col-12">
                        <div class="site-footer-wrap d-flex align-items-center">
                            <p class="copyright-text mb-0 me-4">Copyright © 2036 School Store Co., Ltd.</p>

                            <ul class="social-icon">
                                <li><a href="https://facebook.com" class="social-icon-link bi-facebook"></a></li>

                                <li><a href="https://pinterest.com" class="social-icon-link bi-pinterest"></a></li>

                                <li><a href="https://twitter.com" class="social-icon-link bi-twitter"></a></li>

                                <li><a href="https://www.youtube.com/@inmakeslearninghub" class="social-icon-link bi-youtube"></a></li>
                            </ul>

                        </div>
                    </div>

                    <div class="col-lg-6 col-12">
                    	<p class="copyright-text mb-0 me-4">School Store <a href="#"></a></p>
                    </div>

                </div>
            </div>
        </footer>

        <!-- JAVASCRIPT FILES -->
        <script src="{% static 'js/jquery.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/jquery.sticky.js' %}"></script>
        <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
        <script src="{% static 'js/magnific-popup-options.js' %}"></script>
        <script src="{% static 'js/click-scroll.js' %}"></script>
        <script src="{% static 'js/custom.js' %}"></script>

{% endblock %}

free_project/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block body %}

        <main>

            <section class="hero">
                <div class="container-fluid h-100">
                    <div class="row h-100">

                        <div id="carouselExampleCaptions" class="carousel carousel-fade hero-carousel slide" data-bs-ride="carousel">
                            <div class="carousel-inner">
                                <div class="carousel-item active">
                                    <div class="container position-relative h-100">
                                        <div class="carousel-caption d-flex flex-column justify-content-center">
                                            <small class="small-title">Introducing new courses <strong class="text-warning">01/05</strong></small>

                                            <h1>Inspiring <span class="text-warning">Lifelong</span> Learning School store</h1>

                                            <div class="d-flex align-items-center mt-4">
                                                <a class="custom-btn btn custom-link" href="{% url 'freeapp:login' %}">Join with us</a>

<!--                                                <a class="popup-youtube custom-icon d-flex ms-4" href="https://youtu.be/6HVYX8FRSGA">-->
<!--                                                    <i class="bi-play play-icon d-flex m-auto text-white"></i>-->
<!--                                                </a>-->
                                            </div>
                                        </div>
                                    </div>

                                    <div class="carousel-image-wrap">
                                        <img src="{% static 'images/slide/student.jpg' %}" class="img-fluid carousel-image" alt="">
                                    </div>
                                </div>

                                <div class="carousel-item">
                                    <div class="container position-relative h-100">
                                        <div class="carousel-caption d-flex flex-column justify-content-center">
                                            <small class="small-title">Supporting New Project <strong class="text-warning">01/05</strong></small>

                                            <h1>Transforming Dreams  <span class="text-warning">into Reality</span></h1>

                                            <div class="d-flex align-items-center mt-4">
                                                <a class="custom-btn btn custom-link" href="{% url 'freeapp:login' %}">Explore Capabilities</a>

<!--                                                <a class="popup-youtube custom-icon d-flex ms-4" href="https://www.youtube.com/watch?v=VStvZjykQ00">-->
<!--                                                    <i class="bi-play play-icon d-flex m-auto text-white"></i>-->
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                    
                                    <div class="carousel-image-wrap">
                                        <img src="{% static 'images/slide/jason-goodman-0K7GgiA8lVE-unsplash.jpg' %}" class="img-fluid carousel-image" alt="">
                                    </div>
                                </div>

                                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
                                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                    <span class="visually-hidden">Previous</span>
                                </button>

                                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
                                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                    <span class="visually-hidden">Next</span>
                                </button>
                            </div>
                        </div>

                    </div>
                </div>
            </section>


            <section class="about section-padding" id="section_2">
                <div class="container">
                    <div class="row">

                        <div class="col-lg-6 col-12 mb-5 mb-lg-0">
                            <div class="about-image-wrap h-100">
                                <img src="{% static 'images/student.jpg' %}" class="img-fluid about-image" alt="">

                                <div class="about-image-info">
                                    <h4 class="text-white">School Store</h4>

                                    <p class="text-white mb-0">Describe the facilities available, such as classrooms, labs, libraries, sports facilities, etc</p>
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-6 col-12 d-flex flex-column">
                            <div class="about-thumb bg-white shadow-lg">

                                <div class="about-info">
                                    <small class="small-title">About <strong class="text-warning">02/05</strong></small>

                                    <h2 class="mb-3">School Store</h2>

                                    <h5 class="mb-3">Helping every one since 2001</h5>

                                    <p>Embark on a transformative educational journey with School Store, where excellence meets innovation, and students thrive in an environment dedicated to shaping future leaders</p>

                                    <p>You may support a little   visiting our contact page. Thank you.</p>
                                </div>
                            </div>

                            <div class="row h-100">
                                <div class="col-lg-6 col-6">
                                    <div class="about-thumb d-flex flex-column justify-content-center bg-danger mb-lg-0 h-100">

                                        <div class="about-info">
                                            <h5 class="text-white mb-4">We're growing </h5>

                                            <a class="custom-btn btn custom-bg-primary" href="{% url 'freeapp:login' %}">Join us</a>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-lg-6 col-6">
                                    <div class="about-thumb d-flex flex-column justify-content-center bg-warning mb-lg-0 h-100">

                                        <div class="about-info">
                                            <h5 class="text-white mb-4">How did you about us?</h5>

                                            <p class="text-white mb-0">write us</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </section>



        </main>

        <footer class="site-footer">
            <div class="container">
                <div class="row">
                        
                    <div class="col-lg-6 col-12">
                        <div class="site-footer-wrap d-flex align-items-center">
                            <p class="copyright-text mb-0 me-4">Copyright © 2036 School Store Co., Ltd.</p>

                            <ul class="social-icon">
                                <li><a href="https://facebook.com" class="social-icon-link bi-facebook"></a></li>

                                <li><a href="https://pinterest.com" class="social-icon-link bi-pinterest"></a></li>
    
                                <li><a href="https://twitter.com" class="social-icon-link bi-twitter"></a></li>
    
                                <li><a href="https://www.youtube.com/@inmakeslearninghub" class="social-icon-link bi-youtube"></a></li>
                            </ul>
                            
                        </div>
                    </div>
                    
                    <div class="col-lg-6 col-12">
                    	<p class="copyright-text mb-0 me-4">School Store <a href="#"></a></p>
                    </div>

                </div>
            </div>
        </footer>

        <!-- JAVASCRIPT FILES -->
        <script src="{% static 'js/jquery.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/jquery.sticky.js' %}"></script>
        <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
        <script src="{% static 'js/magnific-popup-options.js' %}"></script>
        <script src="{% static 'js/click-scroll.js' %}"></script>
        <script src="{% static 'js/custom.js' %}"></script>

{% endblock %}

free_project/templates/student_form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="{% static 'css/stdns.css' %}" rel="stylesheet">
    <title>Form Requirements</title>
</head>
<body>
    <div class="container">
         <h1>Fill the Form</h1>

         <form action="{% url 'formapp:students' %}" method="POST">
              {% csrf_token %}
              <div class="input-box">
                  <div>
                       <span class="details">Name:</span>
                       <input type="text" id="name" name="name" placeholder="Enter Your Name" required>
                  </div>
                  <div>
                        <span class="details">Date of Birth:</span>
                        <input type="date" id="dob" name="dob" required>
                  </div>
                  <div>
                        <span class="details">Age:</span>
                        <input type="number" id="age" name="age" required>
                  </div>
              </div><br>
              <div class="input-box">

                  <div class="zero">
                       <span class="details">Gender:</span>
                      <div class="gender">
                            <span class="details">Male:</span>
                            <input type="radio" id="male" name="gender" value="male" required>
                      </div>
                      <div class="gender">
                           <span class="details">Femail:</span>
                           <input type="radio" id="female" name="gender" value="female" required>
                      </div>

                  </div>
                  <div>
                      <span class="details">Phone Number:</span>
                      <input type="number" id="phone" name="phone" placeholder="Enter Your Phone number" required>
                  </div>
                  <div>
                      <span class="details">Email:</span>
                      <input type="email" id="email" name="email" placeholder="Enter Email" required>
                  </div>
              </div><br>

              <div class="input-box">
                 <span class="details">Address:</span>
                 <textarea id="address" name="address" placeholder="Enter Your Address" required></textarea>

                   <span class="details">Department:</span>
                   <select id="department" name="department" required>
                        <option value="computer_science">Computer Science</option>
                        <option value="biology_science">BiologyScience</option>
                        <option value="maths_commerce">Maths Commerce</option>
                        <option value="computer_commerce">Computer Commerce</option>
                        <option value="humanities">Humanities</option>
                   </select>
              </div><br>
              <div class="input-box">
                   <span class="details">Course:</span>
                   <select id="course" name="course" required>
               <!-- Course options will be populated dynamically based on department selection using JavaScript -->
                   </select>

                 <span class="details">Purpose:</span>
                 <select id="purpose" name="purpose" required>
                      <option value="enquiry">Enquiry</option>
                      <option value="placeOrder">Appointment</option>
                      <option value="return">Donation</option>
                 </select>
              </div><br>
              <div class="input-box">
                    <span class="details">Materials Provide:</span>
                  <div>
                        <input type="checkbox" id="notebook" name="materials" value="notebook">
                        <label for="notebook">Debit Note Book</label>
                        <input type="checkbox" id="pen" name="materials" value="pen">
                        <label for="pen">Pen</label>
                        <input type="checkbox" id="papers" name="materials" value="papers">
                        <label for="papers">Exam Papers</label>
                  </div>
              </div><br>
                    <input class="btn btn-primary" type="submit" value="submit">
<!--        <input type="button" value="Logout">-->
            <a class="btn btn-primary" href="{% url 'freeapp:logout' %}">Logout</a>


        </form>

        {% for msg in messages %}
          {{msg}}
        {% endfor %}<br>
        <a href="{% url 'freeapp:demo' %}">Return to Home Page</a>
    </div>
    <script>
        // JavaScript for populating course options based on department selection
        document.getElementById('department').addEventListener('change', function() {
            var department = this.value;
            var courseSelect = document.getElementById('course');
            courseSelect.innerHTML = '';

            if (department === 'computer_science') {
                var options = ['B.Tech', 'BCA', 'BSc IT'];
            } else if (department === 'biology_science') {
                var options = ['B.VSc', 'BSc Nursing', 'BSc Microbiology'];
            } else if (department === 'maths_commerce') {
                var options = ['BA', 'BSc','BDS'];
            }else if (department === 'computer_commerce') {
                var options = ['BBA', 'BCom', 'Accounting',];
            }else if (department === 'humanities') {
                var options = ['B.Com.LLB', 'B.B.A', 'B.H.M'];
            }

            for (var i = 0; i < options.length; i++) {
                var option = document.createElement('option');
                option.value = options[i];
                option.text = options[i];
                courseSelect.appendChild(option);
            }
        });
    </script>

</body>
</html>